= Almighty Developer Documentation

Welcome to the Almighty developer documentation site.

Almighty is a project started by Red Hat to create an opensource ALM covering
the lifecycle from ideation, development, production to sunsetting of an application.

We are still getting started, so bear with us :)

For now, the site is for documenting our process and to keep track of the work we
have done.

Some links might not be fully public, but we will get them moved over as soon as possible.

== Communication

We are currently on hipchat (almighty room), with plans on moving to a publicly hosted mattermost or similar platform soon(tm)!

Mailing list - we have a public mailing list `mailto:almighty-public@redhat.com[almighty-public@redhat.com]`.  You may subscribe `https://www.redhat.com/mailman/listinfo/almighty-public[here]`.

== Team

[format="csv", options="header"]
|===
Name, Role, Areas, Time, Time Zone
https://github.com/maxandersen[Max Rydahl Andersen], Manager/Lead, , 75%, CET
https://github.com/qodfathr[Todd A. Mancini], Product Manager, ,10%, EST
https://github.com/aslakknutsen[Aslak Knutsen], Dev Lead, Backend, 100%, CET
https://github.com/tsmaeder[Thomas Maeder], Dev, Backend, 100%, CET
https://github.com/joshuawilson[Joshua Wilson], Dev, UI, 100%, EST
https://github.com/DhritiShikhar[Dhriti Shikhar], Dev intern, Backend, 100%, IST
https://github.com/Mgranfie[Monica Granfield], UX Lead, , 100%, EST
Josephine Qian, UX, , 50%, EST
Sarajane Clark (Sj), User Research + UX, , 20%, EST
https://github.com/mindreeper2420[Adam Jolicoeur], Interaction Designer, , 100%, EST
https://github.com/gunjansobhani[Gunjan Sobhani], UX Intern, , TBD%, EST
https://github.com/Ritsyy[Richa Rupela], Dev intern, Backend, 100%, IST
https://github.com/kwk[Konrad Kleine], Dev, Backend, 100%, CET
Ranjith Varakan, Scrum Master, , , IST
https://github.com/ldimaggi[Len DiMaggio], QE, UI/Backend, 50%, EST
https://github.com/sbose78[Shoubhik Bose], Dev, Backend, 100%, IST
https://github.com/pranavgore09[Pranav Gore], Dev, Backend, 100%, IST
https://github.com/baijum[Baiju Muthukadan], Dev, Backend, 100%, IST
https://github.com/nimishamukherjee[Nimisha Mukherjee], Dev, UI, 100%, IST
https://github.com/dustymabe[Dusty Mabe], Dev, Containers, 20%, EST
https://github.com/naina-verma[Naina Verma], QE, ALM/Plan, 50%, IS
https://github.com/pradeepto[Pradeepto Bhattacharya], Dev, Deploy, 20%, IST
https://github.com/sanbornsen[Sudipta Sen], Dev, UI, 100%, IST
|===


(If you feel you are missing from the above list, please make a pull-request to update.)

== Resources

[format="csv", options="header"]
|===
Resources, Comment
http://devdoc.almighty.io/, devdoc website (where this gets published)
https://projects.invisionapp.com/share/RD7QIB3QY#/screens[Invision prototypes], Ask Monica about access if you need
https://trello.com/b/sRsGpP8m/alm-track-manage-design-project[UX Trello], Private - should be moved soon
https://trello.com/b/MHDVMYyz/team-alm-plan[Team ALM Trello board], Private - should be moved to Almighty ASAP
|===
